// <auto-generated />
using Capstone.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Capstone.Migrations
{
    [DbContext(typeof(CapstoneDBContext))]
    [Migration("20180607024733_Initial Migration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Capstone.Models.Patient", b =>
                {
                    b.Property<int>("PatientID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Exam");

                    b.Property<string>("Frames");

                    b.Property<string>("Lenses");

                    b.Property<int>("ProviderID");

                    b.Property<string>("Type")
                        .IsRequired();

                    b.HasKey("PatientID");

                    b.HasIndex("ProviderID");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("Capstone.Models.Prefix", b =>
                {
                    b.Property<int>("PrefixID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("ProviderID");

                    b.HasKey("PrefixID");

                    b.HasIndex("ProviderID");

                    b.ToTable("Prefixes");
                });

            modelBuilder.Entity("Capstone.Models.Provider", b =>
                {
                    b.Property<int>("ProviderID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AuthNote");

                    b.Property<string>("BenefitRenewal");

                    b.Property<string>("EligibilityExpiry");

                    b.Property<string>("MiscNotes");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("PagesToSave");

                    b.Property<int>("PatientID");

                    b.Property<string>("PhoneNumber")
                        .IsRequired();

                    b.Property<string>("Plan");

                    b.Property<int>("PrefixID");

                    b.Property<string>("SavedPagesDescription");

                    b.Property<string>("SubscriberNumber");

                    b.HasKey("ProviderID");

                    b.ToTable("Providers");
                });

            modelBuilder.Entity("Capstone.Models.Store", b =>
                {
                    b.Property<int>("StoreID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("PhoneNumber")
                        .IsRequired();

                    b.HasKey("StoreID");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("Capstone.Models.Patient", b =>
                {
                    b.HasOne("Capstone.Models.Provider")
                        .WithMany("Patients")
                        .HasForeignKey("ProviderID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Capstone.Models.Prefix", b =>
                {
                    b.HasOne("Capstone.Models.Provider", "Provider")
                        .WithMany("Prefixes")
                        .HasForeignKey("ProviderID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
